name: Wastewater Catchment Areas
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 9 * * 1"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Download the data from the web archive.
        run: |
          make -j 4 data
          make data/validation
      - name: Run the analysis.
        run: make analysis
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          body_path: release_body.md
          files: |
            data/wastewater_catchment_areas_public/catchments_consolidated.zip
            data/wastewater_catchment_areas_public/*.csv
